package com.james.demo.mybatis.mapper;

import com.james.demo.mybatis.model.WpUsers;
import com.james.demo.mybatis.model.WpUsersExample;
import java.util.List;

import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

@Mapper
public interface WpUsersMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    long countByExample(WpUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int deleteByExample(WpUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int insert(WpUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int insertSelective(WpUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    List<WpUsers> selectByExample(WpUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    WpUsers selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int updateByExampleSelective(@Param("record") WpUsers record, @Param("example") WpUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int updateByExample(@Param("record") WpUsers record, @Param("example") WpUsersExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int updateByPrimaryKeySelective(WpUsers record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wp_users
     *
     * @mbg.generated Tue Mar 06 15:37:27 CST 2018
     */
    int updateByPrimaryKey(WpUsers record);
}